document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" name=\"searchform\" method=\"get\" action=\"http://wmw.qnz.com.cn/search.html\" _lpchecked=\"1\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"t\" id=\"m_t\">')
document.writeln('        <option value=\"1\">标 题</option>')
document.writeln('        <option value=\"7\">简 介</option>')
document.writeln('        <option value=\"2\">内 容</option>')
document.writeln('        <option value=\"3\">作 者</option>')
document.writeln('        <option value=\"4\">录入者</option>')
document.writeln('        <option value=\"5\">关键字</option>')
document.writeln('        <option value=\"8\">发布时间</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"tid\" id=\"m_tid\" style=\"width:150px\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'664\'>文明创建 </option><option value=\':1209\'>──动漫资讯 </option><option value=\'832\'>文明播报 </option><option value=\'1237\'>多彩贵州文明行动 </option><option value=\'1532\'>四在农家美丽乡村 </option><option value=\'1533\'>黔南骄傲 </option><option value=\'1534\'>道德模范 </option><option value=\'1535\'>志愿服务 </option><option value=\'1536\'>我们的节日 </option><option value=\'1537\'>道德讲堂 </option><option value=\'1538\'>工作信息 </option><option value=\'1539\'>讲文明树新风 </option><option value=\'1540\'>未成年人教育 </option><option value=\'1541\'>图片 </option><option value=\'1542\'>资料 </option><option value=\'1543\'>访谈 </option><option value=\'1544\'>视频 </option><option value=\'1545\'>头条 </option><option value=\'1546\'>机关工作 </option><option value=\'1547\'>专题专栏 </option><option value=\'1547:1549\'>──乡村环境整治建设美丽黔南 </option>        </select>')
document.writeln('        <input name=\"word\" type=\"text\" id=\"word\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input type=\"submit\" onclick=\"\" class=\"inputButton\"  value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
